name: Trigger update to partners.pactflow.io

on:
  push:
    branches:
      - master
    paths:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger partner.pactflow.io update workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GHTOKENFORTRIGGERINGPACTDOCSUPDATE }}
          repository: pactflow/partners.pactflow.io
          event-type: pactflow-example-consumer-python-updated